FROM         --platform=$TARGETOS/$TARGETARCH alpine:latest

LABEL        author="Fleter" maintainer="fleter@fleter.my.id"
LABEL        org.opencontainers.image.source="https://github.com/pterodactyl/yolks"
LABEL        org.opencontainers.image.licenses=MIT

RUN         apk add --update --no-cache ca-certificates curl unzip tar git jq wget