name: Java (specified)
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - docker-image/java/**
jobs:
  push:
    name: "Azul Zulu - Java (version: ${{ matrix.azul-zulu }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        azul-zulu:
          - 21-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN_GITHUB }}
      - uses: docker/build-push-action@v5
        with:
          context: ./docker-image/java
          file: ./docker-image/java/azul-zulu/${{ matrix.azul-zulu }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/fleters/docker-image:zulu-${{ matrix.azul-zulu }}
