name: Database (MariaDB)
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - docker-image/os/**
jobs:
  push:
    name: "Database (version: MariaDB-${{ matrix.version }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN_GITHUB }}
      - uses: docker/build-push-action@v5
        with:
          context: ./docker-image/database/mariadb
          file: ./docker-image/database/mariadb/${{ matrix.version }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/fleters/docker-image:db-mariadb-${{ matrix.version }}
