name: PHP (.phar)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docker-image/php/**
jobs:
  push:
    name: "PHP (version: ${{ matrix.tag }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - latest
    steps:
      - uses: actions/checkout@v4
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN_GITHUB }}
      - uses: docker/build-push-action@v5
        with:
          context: ./docker-image/php
          file: ./docker-image/php/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/fleters/docker-image:php-${{ matrix.tag }}
