# name: Building Experiment
# on:
#   workflow_dispatch:
# jobs:
#   build_and_publish:
#     strategy:
#       fail-fast: false
#       matrix:
#         tag:
#           - latest
#     runs-on: ubuntu-latest
#     name: "Building Experiment (version: ${{ matrix.tag }})"
#     steps:
#       - uses: actions/checkout@v3
#       - run: |
#           cd docker-image/experiment/
#           ls
#           echo "---"
#           docker login --username fleters --password ${{ secrets.TOKEN_GITHUB }} ghcr.io
#           docker build ./${{ matrix.tag }} --tag ghcr.io/fleters/experiment:${{ matrix.tag }}
#           docker push ghcr.io/fleters/experiment:${{ matrix.tag }}


name: Building Experiment
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - docker-image/experiment/**
jobs:
  push:
    name: "Building Experiment (version: ${{ matrix.tag }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - latest
    steps:
      - uses: actions/checkout@v4
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN_GITHUB }}
      - uses: docker/build-push-action@v5
        with:
          context: ./docker-image/experiment
          file: ./docker-image/experiment/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/fleters/experiment:${{ matrix.tag }}
